
all: rtgen rtdump rtsort rcrack

rtgen:
	g++ Public.cpp ChainWalkContext.cpp HashAlgorithm.cpp HashRoutine.cpp RainbowTableGenerate.cpp -lssl -O3 -o rtgen

rtdump:
	g++ Public.cpp ChainWalkContext.cpp HashAlgorithm.cpp HashRoutine.cpp RainbowTableDump.cpp -lssl -o rtdump

rtsort:
	g++ Public.cpp RainbowTableSort.cpp -o rtsort

rcrack:
	g++ Public.cpp ChainWalkContext.cpp HashAlgorithm.cpp HashRoutine.cpp HashSet.cpp MemoryPool.cpp ChainWalkSet.cpp CrackEngine.cpp RainbowCrack.cpp -lssl -o rcrack


install:
	@echo Installing rainbowcrack to /usr/local/bin/
	@cp ./rtgen /usr/local/bin/
	@cp ./rtdump /usr/local/bin/
	@cp ./rtsort /usr/local/bin/
	@cp ./rcrack /usr/local/bin/

deinstall:
	@echo Removing rainbowcrack from /usr/local/bin/
	@rm -f bin/rtgen
	@rm -f bin/rtdump
	@rm -f bin/rtsort
	@rm -f bin/rcrack
	@echo done.

distclean: clean


clean:
	@echo Cleaning up...
	-rm -f rainbowcrack-1.2
	@echo done.

