# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "popular_matches", :force => true do |t|
    t.column "hits", :integer
    t.column "hash", :string
    t.column "text", :string
    t.column "updated_on", :datetime
    t.column "created_on", :datetime
  end

  create_table "webrts", :force => true do |t|
    t.column "gstring", :string
    t.column "lmhash", :string, :default => "", :null => false
    t.column "lmhash_half1", :string, :default => "", :null => false
    t.column "lmhash_half2", :string
    t.column "status", :string
    t.column "text", :string
    t.column "text_half1", :string
    t.column "text_half2", :string
    t.column "cracked_half1", :boolean, :default => false
    t.column "cracked_half2", :boolean, :default => false
    t.column "email", :string
    t.column "ip_address", :string
    t.column "elapsed_time", :string
    t.column "created_on", :datetime
  end

end
